package com.ihsinformatics.aahung.common;

public class Keys {

    public static final String DONOR_ID = "donorId";
    public static final String DONOR_NAME = "donarName";
    public static final String PROPOSAL_NAME = "proposalName";
    public static final String DATE_GRANT_BEGINS = "dateGrantBegins";
    public static final String DATE_GRANT_ENDS = "dateGrantEnds";
    public static final String PROVINCE = "province";
    public static final String DISTRICT = "district";
    public static final String PARENT_ORGANISATION_ID = "parentOrganizationID";
    public static final String PARENT_ORGANISATION_NAME = "parentOrganizationName";
    public static final String SCHOOL_ID = "schoolId";
    public static final String SCHOOL_NAME = "schoolName";
    public static final String SCHOOL_TYPE = "schoolType";
    public static final String SCHOOL_CLASSIFICATION = "schoolClassification";
    public static final String LEVEL_OF_PROGRAM = "programLevel";
    public static final String SCHOOL_TIER = "schoolTier";
    public static final String NEW_SCHOOL_TYPE = "newSchoolCategory";
    public static final String RUNNING_SCHOOL_TYPE = "runningSchoolCategory";
    public static final String EXIT_SCHOOL_TYPE = "exitSchoolCategory";
    public static final String TYPE_OF_PROGRAM_IN_SCHOOL = "typeOfProgramInSchool";
    public static final String PHONE_NUMBER = "phoneNumber";
    public static final String EMAIL = "email";
    public static final String APPROX_STUDENTS = "approxNumberOfStudent";
    public static final String TEACHER_ID = "teacherId";
    public static final String TEACHER_NAME = "teacherName";
    public static final String AGE = "age";
    public static final String SEX = "sex";
    public static final String SUBJECT = "subjects";
    public static final String OTHER = "other";
    public static final String TEACHING_YEARS = "teachingYears";
    public static final String EDUCATION_LEVEL = "educationLevel";
    public static final String MONITORED_BY = "monitoredBy";
    public static final String DATE = "date";
    public static final String CLASS_CLASSIFICATION = "classClassification";
    public static final String PRIMARY_PROGRAM = "primaryProgram";
    public static final String CLASS = "class";
    public static final String NUMBER_OF_STUDENDS = "noOfStudents";
    public static final String DURATION_OF_CLASS = "durationOfClass";
    public static final String CSA_FLASHCARD = "CSAFlashCard";
    public static final String CSA_REVISION_OR_FIRSTTIME = "csaRevisionOrFirstTime";
    public static final String TEACHER_USING_FLASHCARD = "teacherUsingFlashcard";
    public static final String TEACHER_HAD_MATERIAL = "teacherHadMaterial";
    public static final String TEACHER_MEETING_OBJECTIVE = "teacherMeetingObjective";
    public static final String TEACHER_WELL_PREPARED = "teacherWellPrepared";
    public static final String TIME_ALLOTED_FOR_ACTIVITY = "timeAllotedForActivity";
    public static final String TEACHER_COMFORTABLE_SPEAKING = "teacherComfortableSpeaking";
    public static final String TEACHER_JUDGEMENTAL_TONE = "teacherJudgementalTone";
    public static final String TEACHER_OWN_OPINIONS = "teacherOwnOpinions";
    public static final String STUDENTS_ENGAGEMENT = "studentDiscussion";
    public static final String STUDENTS_UNDERSTAND_MESSAGE = "studentUnderstandTheMessage";
    public static final String STUDENTS_PAYING_ATTENTION = "studentPayingAttention";
    public static final String MANAGEMENT_INTEGRATED_CSA = "managementIntegratedCSA";
    public static final String CLASS_FREQUENCY = "classFrequency";
    public static final String EXCELLENT_COORDINATION = "excellentCoordination";
    public static final String MONITORING_SCORE = "monitoringScore";
    public static final String MONITORING_SCORE_PERCENTAGE = "percentageOfMonitoringScore";
    public static final String CHALLENGE_SCHEDULING_CSA = "challengeSchedulingCSA";
    public static final String CHALLENGE_SCHEDULING_CSA_STATUS = "challengeStatus";
    public static final String ENOUGH_RESOURCES = "enoughResources";
    public static final String DATE_PARTNERSHIP_STARTED = "datePartnershipStarted";
    public static final String DATE_PARTNERSHIP_ENDED = "datePartnershipEnded";
    public static final String PARTNERSHIP_YEARS = "partnershipYears";
    public static final String REASON_PARTNERSHIP = "reasonPartnership";
    public static final String CSA_PROGRAM_SCORE = "CSAProgramScore";
    public static final String TWO_TEACHER_CSA = "twoTeacherCSA";
    public static final String ENOUGH_RESOURCES_STATUS = "stateOfChallenge";
    public static final String NO_ROOM_FOR_CLASS = "noRoomForClass";
    public static final String NO_ROOM_STATUS = "noRoomStatus";
    public static final String NO_TEACHER_FOR_CLASS = "noTeacherForClass";
    public static final String NO_TEACHER_STATUS = "noTeacherStatus";
    public static final String IRRELEVENT_CONTENT = "irreleventContent";
    public static final String IRRELEVENT_CONTENT_STATUS = "irreleventContentStatus";
    public static final String STUDENT_NOT_INTERESTED = "studentNotInterested";
    public static final String STUDENT_NOT_INTERESTED_STATUS = "studentNotInterestedStatus";
    public static final String SCHOOL_REQUIRE_RESOURCES = "schoolRequireResources";
    public static final String CSA_RESOURCES_REQUIRE_FLASHCARD_GUIDES = "csaResourceRequireFlashCardGuides";
    public static final String CSA_RESOURCES_REQUIRE_DRAWING_BOOKS = "csaResourceRequireDrawingBooks";
    public static final String CSA_RESOURCES_REQUIRE_OTHER = "csaResourceRequireOther";

    public static final String CSA_SCHOOL_RESOURCES_DISTRIBUTED = "csaResourceDistribute";
    public static final String CSA_RESOURCES_DISTRIBUTED_FLASHCARD_GUIDES = "csaResourceDistributeFlashCardGuides" ;
    public static final String CSA_RESOURCES_DISTRIBUTED_DRAWING_BOOKS = "csaResourceDistributeDrawingBooks";
    public static final String CSA_RESOURCES_DISTRIBUTED_OTHER = "csaResourceDistributeOther";

    public static final String GENDER_FLASHCARD_RUN = "genderFlashCardRun";
    public static final String GENDER_REVISION_OR_FIRSTTIME = "genderRevisionOrFirstTime";

    public static final String GENDER_PROGRAM_SCORE = "genderProgramScore";

    public static final String GENDER_TEACHER_USING_FLASHCARD = "genderTeacherUsingFlashcard";
    public static final String GENDER_TEACHER_HAD_MATERIAL = "genderTeacherHadMaterial";
    public static final String GENDER_TEACHER_MEETING_OBJECTIVE = "genderTeacherMeetingObjective";
    public static final String GENDER_TEACHER_WELL_PREPARED = "genderTeacherWellPrepared";
    public static final String GENDER_TIME_ALLOTED_FOR_ACTIVITY = "genderTimeAllotedForActivity";
    public static final String GENDER_TEACHER_COMFORTABLE_SPEAKING = "genderTeacherComfortableSpeaking";
    public static final String GENDER_TEACHER_JUDGEMENTAL_TONE = "genderTeacherJudgementalTone";
    public static final String GENDER_TEACHER_OWN_OPINIONS = "genderTeacherOwnOpinions";
    public static final String GENDER_STUDENTS_ENGAGEMENT = "genderStudentDiscussion";
    public static final String GENDER_STUDENTS_UNDERSTAND_MESSAGE = "genderStudentUnderstandTheMessage";
    public static final String GENDER_STUDENTS_PAYING_ATTENTION = "genderStudentPayingAttention";
    public static final String GENDER_MANAGEMENT_INTEGRATED_CSA = "genderManagementIntegratedCSA";
    public static final String GENDER_CLASS_FREQUENCY = "genderClassFrequency";
    public static final String GENDER_EXCELLENT_COORDINATION = "genderExcellentCoordination";
    public static final String GENDER_OTHER = "genderOther";
    public static final String GENDER_TWO_TEACHER_CSA = "genderTwoTeachers";
    public static final String CHALLENGE_SCHEDULING_GENDER = "genderScheduleChallenge";

    public static final String GENDER_RESOURCES_REQUIRE_FLASHCARD_GUIDES = "genderResourceRequireFlashCardGuides";
    public static final String GENDER_RESOURCES_REQUIRE_DRAWING_BOOKS = "genderResourceRequireDrawingBooks";
    public static final String GENDER_RESOURCES_REQUIRE_OTHER = "genderResourceRequireOther";

    public static final String GENDER_SCHOOL_RESOURCES_DISTRIBUTED = "genderResourceDistribute";
    public static final String GENDER_RESOURCES_DISTRIBUTED_FLASHCARD_GUIDES = "genderResourceDistributeFlashCardGuides" ;
    public static final String GENDER_RESOURCES_DISTRIBUTED_DRAWING_BOOKS = "genderResourceDistributeDrawingBooks";
    public static final String GENDER_RESOURCES_DISTRIBUTED_OTHER = "genderResourceDistributeOther";

    public static final String NEW_ACTIVITIES = "newActivities";
    public static final String TEACHERS_NEW = "teachersNew";
    public static final String SESSION_ID = "sessionId";
    public static final String MASTER_TRAINERS = "masterTrainers";
    public static final String COORDINATION_WITH_MASTER_TRAINERS = "coordinationWithMasterTrainer";
    public static final String MASTER_TRAINER_CONDUCT_SESSION = "masterTrainerConductSession";
    public static final String MASTER_TRAINER_REFRESHER_TRAINING = "masterTrainerRefresherTraining";
    public static final String LSBE_LEVEL = "lsbeLevel";
}
